
// Generated by xt-genmpu.

#include <stdint.h>
#include <xtensa/hal.h>

#if defined (__cplusplus)
extern "C"
#endif
const struct xthal_MPU_entry
__xt_mpu_init_table[] __attribute__((section(".ResetHandler.text"))) = {
  XTHAL_MPU_ENTRY(0x00000000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
  XTHAL_MPU_ENTRY(0x00080000, 1, XTHAL_AR_RWrw, XTHAL_MEM_NON_CACHEABLE), // dram0
  XTHAL_MPU_ENTRY(0x00100000, 1, XTHAL_AR_RWXrwx, XTHAL_MEM_NON_CACHEABLE), // iram0
  XTHAL_MPU_ENTRY(0x00200000, 1, XTHAL_AR_NONE, XTHAL_MEM_DEVICE), // unused
};

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_table_size __attribute__((section(".ResetHandler.text"))) = 4;

#if defined (__cplusplus)
extern "C"
#endif
const uint32_t __xt_mpu_init_cacheadrdis __attribute__((section(".ResetHandler.text"))) = 0x000000ff;

#if defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)
#include <assert.h>
static_assert(sizeof(__xt_mpu_init_table)/sizeof(__xt_mpu_init_table[0]) == 4, "Incorrect MPU table size");
#endif
